version: "3.7"
services:
  client:
    command: "-f /dev/null"
    entrypoint: /usr/bin/tail
    tty: true
    image: alpine/curl

  router:
    privileged: true
    tty: true 
    build:
      context: ./
      dockerfile: Dockerfile-router

  taget-A:
    image: nginxdemos/hello:plain-text
    hostname: target-A

  taget-B:
    image: nginxdemos/hello:plain-text
    hostname: target-B
