#!/bin/bash

#Docker
echo '{ "ipv6": true, "fixed-cidr-v6": "fd00::/80"}' > /etc/docker/daemon.json
sudo apt-get update
sudo apt-get install ca-certificates curl gnupg lsb-release
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io git -y

#Tutorial prep 
git clone https://github.com/asayah/ebpf-xdp-tutorial tutorial
cd tutorial
./prepare.sh